### ISSUE TITLE
Not working offline

### ISSUE THREAD

**Issue by smlswhl** [rtpHarry/Bootstrap3-ShowManySlideOneCarousel#1]
The demo works for me at all the links online (bootply, codepen, your test url), but when I download it I only see 1 item at a time in the carousel

![screen shot 2015-05-19 at 11 06 44 pm](https://cloud.githubusercontent.com/assets/75953/7718264/c0e502d8-fe7b-11e4-9362-f71ec8295340.png)

Ideas? Thanks!

**Comment by rtpHarry** [comment]
I can see that the CSS styles are not being applied. 
1. Your code should have this line in it:
   
   ```
   <link rel='stylesheet' href='dist/css/1.0.0/bootstrap3-showmanyslideonecarousel.min.css'>
   ```
2. The file at `dist/css/1.0.0/bootstrap3-showmanyslideonecarousel.min.css` must exist. 

Can you check that these two items are true? If your folder setup is not the same then you might need to change the path in the href as this is a relative url. 

Happy to help further if you need more clarification.

**Comment by rtpHarry** [comment]
I'm closing this now as its been several months, please feel free to re-open it if you're still having problems.
