### ISSUE TITLE
Weird padding issue and images showing up multiple times

### ISSUE THREAD

**Issue by AriesCZ** [rtpHarry/Bootstrap3-ShowManySlideOneCarousel#2]
First off, thanks for doing probably the best version of this carousel extension.

However, I seem to have some weird isue with it. When the items are being moved, their padding gets messed up, and sometimes, parts of some images get shown twice. When moving is done, it all goes back to normal.

I tried setting solid color background to all .item and its children elements, hoping that it is an issue casued by me seeing the next slide, and I tried setting paddings to 0, but to no avail.

I am using 4 240px wide images in a carousel with max-width 1170px at the most.

See the attached files
![carousel_bug_2](https://cloud.githubusercontent.com/assets/15626972/10903931/53c27c90-820f-11e5-8844-20e0c045cc79.jpg)

On the "color mess" picture (full screen size)

![carousel_bug](https://cloud.githubusercontent.com/assets/15626972/10903934/57c2a630-820f-11e5-9b06-641e50a04f78.jpg)

On the dog picture (smaller window)

Happens in Firefox and Chrome, so probably everywhere...

Thanks for any help you can provide...

**Comment by rtpHarry** [comment]
Thanks for the compliments :)

Is this online anywhere that I can have a poke around with?

When I was developing the carousel I had a bunch of problems with images overlapping like this but I can't really put my finger on what exactly it is from the screenshots.

Basically they way it works is that it creates copies of the next few slides and injects them into the current slide. This means that underneath there is a second copy of the slider which can sometimes escape.

I'm wondering if it could be many things:
- Are your column classes correct for each of the different view sizes? eg `col-sm-4`
- Are the source images big enough to fill the columns?
- It could be that the latest version of bootstrap has a conflict - have you checked which version I said I tested against, does that work for you without these glitches?
- Did you copy all of the styles into your project correctly?

If you can provide some kind of demo that I can play with then I would be happy to investigate further with you.

**Comment by AriesCZ** [comment]
I tried adding full sized images, and this "overlap" problem is gone. However, a new problem, although much less annoying, has replaced it.

Now the picutres sometimes "zoom in" when moving then snap back (I assume this has something to do with them being made responsive by bootstrap).

Testing it, it looks like there might be some issue withspace between the images, as it looks like it is shrinking and resizing...

**Comment by rtpHarry** [comment]
I found a few minutes to look into this today, it seems that if you change this line:

```
<div class="carousel-inner container">
```

to this

```
<div class="carousel-inner">
```

it stops the "zoom in" display glitches you described.
